channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy >=1.25.2
  - gdal >=3.7.0
  - pyramids >=0.5.6
  - geopandas >=0.14.1
  - cleopatra >=0.4.0
  - pytest >=7.4.3
  - pytest-cov >=4.1.0
